[package]
name = "dgressions"
version = "0.1.0"
authors = ["Oguzhan YAGCI <oyagci@student.42.fr>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.58"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
